schema: 'http://localhost:3000/api/graphql'
documents: "pages/**/*.gql"
extensions:
  codegen:
    generates:
      ./generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
          - named-operations-object