import Head from "next/head";
import Dashboard from "./dashboard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ordenfa 2021 Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  );
}
